/**
 * The live site's copy, verbatim (generated by scripts/live-copy.mjs from a scrape of revolt-marketing.com).
 * Every word a visitor reads comes from here; components only decide how it looks.
 */
import siteJson from "./live/site.json";
import systemsJson from "./live/systems.json";
import pagesJson from "./live/pages.json";

export type Link = { text: string; href: string | null };
export type Block =
  | { t: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p"; text: string; lines?: string[]; links?: Link[] }
  | { t: "ul"; items: string[] }
  | { t: "img"; alt: string; src: string }
  | { t: "button"; text: string; href: string | null };
export type TextBlock = Extract<Block, { t: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p" }>;
export type Faq = { q: string; a: string };
export type RichPage = { blocks: Block[]; faq?: Faq[] };
export type LiveSystem = { slug: string; h1: string; intro: string; items: { title: string; text: string; buttons: Link[] }[] };

export const live = siteJson;
export const liveSystems = systemsJson as LiveSystem[];
const pages = pagesJson as unknown as Record<string, RichPage>;

export const richPage = (route: string): RichPage | undefined => pages[route];
export const liveSystem = (slug: string) => liveSystems.find((s) => s.slug === slug);
export const richRoutes = () => Object.keys(pages);
