import type { Metadata } from "next";
import seoJson from "@/content/live/seo.json";

/**
 * The live site's SEO, route by route (generated by scripts/live-copy.mjs): the exact <title>, meta description,
 * canonical, Open Graph and Twitter tags, and the structured data. Pages without a description on the live site
 * have none here either.
 */
type Entry = {
  title: string;
  description: string | null;
  canonical: string;
  og: { title: string | null; description: string | null; type: string | null; siteName: string | null; image: string | null; width: number | null; height: number | null };
  twitter: { card: string | null; title: string | null; description: string | null };
  jsonld: unknown[];
};
const SEO = seoJson as unknown as Record<string, Entry>;
const SITE = "https://www.revolt-marketing.com";
const LOGO = "92bbae_be4011fd8b7b4006ae9dc90cc7b98111";

export function seoFor(route: string): Metadata {
  const e = SEO[route];
  if (!e) return {};
  const image = e.og.image ? [{ url: e.og.image, ...(e.og.width && e.og.height ? { width: e.og.width, height: e.og.height } : {}) }] : undefined;
  return {
    title: { absolute: e.title },
    ...(e.description ? { description: e.description } : {}),
    alternates: { canonical: e.canonical },
    openGraph: {
      ...(e.og.title ? { title: e.og.title } : {}),
      ...(e.og.description ? { description: e.og.description } : {}),
      url: e.canonical,
      ...(e.og.siteName ? { siteName: e.og.siteName } : {}),
      type: e.og.type === "article" ? "article" : "website",
      ...(image ? { images: image } : {}),
    },
    twitter: {
      card: "summary_large_image",
      ...(e.twitter.title ? { title: e.twitter.title } : {}),
      ...(e.twitter.description ? { description: e.twitter.description } : {}),
      ...(e.og.image ? { images: [e.og.image] } : {}),
    },
  };
}

/** Wix-hosted image URLs in the structured data → this site's copies of the same images. */
function rehost(v: unknown): unknown {
  if (typeof v === "string") {
    const m = v.match(/^https:\/\/static\.wixstatic\.com\/media\/([^/~.]+)/);
    if (!m) return v;
    return m[1] === LOGO ? `${SITE}/media/wordmark.png` : `${SITE}/media/blog/${m[1]}.jpg`;
  }
  if (Array.isArray(v)) return v.map(rehost);
  if (v && typeof v === "object") return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, rehost(x)]));
  return v;
}

export function jsonLdFor(route: string): unknown[] {
  return (SEO[route]?.jsonld ?? []).map(rehost);
}
